name: Hourly Light Refresh

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch: {}

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Call light-refresh endpoint
        env:
          BASE_URL: https://alan-chat-proxy.vercel.app
          INGEST_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlnenZ3YnZndm16dnZ6b2NsdWZ4Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1NzY3NzkyOCwiZXhwIjoyMDczMjUzOTI4fQ.W9tkTSYu6Wml0mUr-gJD6hcLMZDcbaYYaOsyDXuwd8M
        run: |
          set -euo pipefail
          echo "Triggering light refresh at $BASE_URL"
          http_code=$(curl -sS -o /tmp/body.txt -w '%{http_code}' \
            -H "Authorization: Bearer ${INGEST_TOKEN}" \
            "$BASE_URL/api/light-refresh?action=run")
          echo "HTTP $http_code"
          cat /tmp/body.txt
          if [ "$http_code" -ge 400 ]; then exit 1; fi


